### ISSUE TITLE
Should existing_google_sso_users even be called that??

### ISSUE THREAD

**Issue by cannontrodder** [aws-ia/terraform-aws-iam-identity-center#46]
Our use case is to provision our users from our AD connection but assign them to groups using terraform, the groups are actually created by terraform too.

When assigning the group names to 'group_membership' to users then passed in to 'existing_sso_users' no group memebership is assigned. However, when looking at the source, I see that there is functionality to assign groups created in terraform to users that are already existing and this is in [sso_group_membership_existing_google_sso_users](https://github.com/aws-ia/terraform-aws-iam-identity-center/blob/7536bb4079fba12d239b61b09f161e8771ec3b4d/main.tf#L145C48-L145C94)

After applying this, groups created in terraform are no assigned correctly to users which already existed.

There seems to be no real reference to 'google' other than in the name and I'm wondering if this is a mistake? 'existing_google_sso_users' seems to be where you attach users if you want to assign them to groups created in your terraform. I wonder if this functionality can somehow be added into 'existing_sso_users' or if the input can be renamed as you'd never consider using it if you did not scour the source code.

**Comment by novekm** [comment]
Hi @cannontrodder,

`existing_google_sso_users` was created to support a use case where Google Workspace is being used as the external Identity Provider. Currently Google Workspace only syncs users (not groups) to AWS IAM Identity Center via SCIM. 

The initial version of the module had two patterns in mind:
1. **Using IAM Identity Store with IAM Identity Center as the IdP, and creating users/groups as well as the permission sets and account assignments to apply to them.**
2. **Using an external IdP (ex. Entra ID, Okta, etc.) and syncing users/groups via SCIM. Create only permission sets and account assignments to apply to synced users/groups.** (most customers we've seen tend to lean to this pattern).

Per #32 there was a request to add support for a third pattern - **syncing only users via SCIM, and creating groups to place those synced users in. Then applying permission sets/account assignments as desired.** At the time, Google Workspace was the only identified IdP that had this limitation (and at the time was the only IdP requested to use the module this way) hence the naming convention.

`existing_sso_users` is the variable that is used to reference these users that were synced with SCIM (for IdPs besides Google), and are processed differently than the`existing_google_sso_users` variable. These were intentionally separated to reduce complexity and improve the readability of the module code. Also under the assumption that if/when Google Workspace supports syncing groups (in addition to users), most customers would tend to prefer just following pattern two (mentioned above). 

This is what we're planning to keep for the foreseeable future, but we are open to recommendations for naming that may make this a bit more clear. Also if you'd like to submit a PR that merges the functionality into `existing_sso_users` we'd be happy to review it!

**Comment by novekm** [comment]
Marking this as closed for now, feel free to open a new GH issue if you have additional feedback, or a PR for review that implements the functionality you're looking for. Thanks!
